import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="w-full h-dvh bg-sky-300">
					<Header />

					<main className="w-full h-screen border-4 border-blue-800 relative">
						<Navbar />
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
