import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-dvh bg-blue-200">
          <Header />
          <main className="w-full h-screen border-4 border-blue-800 relative">
            <Navbar />
            <div className="pl-60 w-full h-[56px] border-4 border-blue-400">
              Tag-container
            </div>
            <div className="grid pl-60 border-4 border-pink-200 gap-3 grid-cols-3">
              <div className="border-4 border-green-600">
                <img src="a1.webp" alt="a1"></img>
              </div>
              <div className="border-4 border-green-600">
                <img src="a1.webp" alt="a1"></img>
              </div>
              <div className="border-4 border-green-600">
                <img src="a1.webp" alt="a1"></img>
              </div>
              <div className="border-4 border-green-600">
                <img src="a1.webp" alt="a1"></img>
              </div>
              <div className="border-4 border-green-600">
                <img src="a1.webp" alt="a1"></img>
              </div>
            </div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
