import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	icons: {
		icon: [
			{
				media: "(prefers-color-scheme: light)",
				url: "/favicon.ico",
				href: "/favicon.ico",
			},
		],
	},
	title: "Next.js Lesson",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<div>
				<body className={inter.className}>{children}</body>
			</div>
		</html>
	);
}
