import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YouTube Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>
        {/* <div>Header</div> */}
        <body className={inter.className}>{children}</body>
        {/* <div>Feader</div> */}
      </div>
    </html>
  );
}
